import { PrismaClient } from "@prisma/client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from 'swr'
 
import React from "react";
import fetcher from "../lib/fetcher";
  
export default function Home(
  
) {
  const { data, error } = useSWR('http://localhost:3000/api/users?limit=10', fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  
   
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main className={styles.main}>
          <h1 className={styles.title}>Users SWR</h1>

         <p> {data.users && data.users.length} Users fetched</p>
       <div>
          {data.users && data.users.map((u) => (
            <li key={u.id}>{u.name}</li>
          ))}
        </div>    
 
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
